# Generated by Django 4.2.5 on 2024-01-23 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='modified_date',
        ),
    ]
