# Generated by Django 4.2.5 on 2024-01-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='views',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
