# Generated by Django 4.2.5 on 2024-01-31 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_customerreview_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreview',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerreview',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
