# Generated by Django 4.2.5 on 2024-01-31 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_customerreview_date_time_alter_customerreview_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerReview',
        ),
    ]
