# Generated by Django 5.0.1 on 2024-03-22 18:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_customerreview_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customerreview',
            unique_together={('user', 'product')},
        ),
    ]
