# Generated by Django 4.2.5 on 2024-01-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_address',
            new_name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='email_address',
            field=models.EmailField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.TextField(default=None, max_length=15),
        ),
    ]
