# Generated by Django 4.2.5 on 2024-01-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_delivery_address_order_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email_address',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.TextField(max_length=15),
        ),
    ]
